DROP TABLE Message;
CREATE TABLE Message (
	id INT AUTO_INCREMENT PRIMARY KEY,
	data TEXT,
	ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE Direct_Message;
CREATE TABLE Direct_Message (
	id INT AUTO_INCREMENT PRIMARY KEY,
	from VARCHAR(1024) NOT NULL,
	to VARCHAR(1024) NOT NULL,
	data TEXT,
	ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

